Move component data wrapper to frequenz.sdk.simulate
frequenz-floss/frequenz-sdk-python pull request #245
Opened 2023-03-09 14:45 UTC by mathias-baumann-frequenz

So it can be used in actors as well.

2023-03-09 14:55 UTC, mathias-baumann-frequenz commented
I have no idea why those tests fail, I cannot reproduce that locally at all. My local `black` is very happy.

2023-03-09 19:07 UTC, ela-kotulska-frequenz approved these changes

2023-03-10 08:27 UTC, leandro-lucarella-frequenz requested changes
I really don't like the name, so just blocking this from being merged until we discuss it.

2023-03-16 14:04 UTC, mathias-baumann-frequenz commented
I am not using this after all now that we have the battery pool

2023-03-16 14:04 UTC, closed without merging